<a href="https://colab.research.google.com/github/SanePai/Neural_Networks-Assignment-2/blob/main/Question_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
%cd "/content/drive/MyDrive/NNFL/Assignment 2"
!ls

/content/drive/.shortcut-targets-by-id/104/Assignment 2
assignment2.pdf  class2_images	class_label.mat  data5.mat     input.mat
class1_images	 class3_images	data55.xlsx	 input_a2.mat  label.mat


In [10]:
import numpy as np 
from scipy.io import loadmat
from sklearn.preprocessing import normalize
import random
from sklearn.metrics import confusion_matrix as cm

In [11]:
#Gaussian activation function
def gaussian(X, a, b):   
    K = np.zeros((X.shape[0], hidden_neurons))
    for i in range(K.shape[0]):
        for j in range(K.shape[1]):
            K[i,j] = np.exp(-b[j] * np.linalg.norm(a[:,j] - X[i,:]))  
    return K

#Tanh activation function
def tanh(X):
    return np.tanh(X)

#Load data, shuffle and normalize
def init_data(data):
    X = np.array(data[ : , :-1], dtype = float)
    y = np.array(data[ : , -1], dtype = int)
    X = normalize(X, axis = 0)
    return X, y

In [12]:
f = loadmat('data5.mat')
D = f['x']
np.random.shuffle(D)

X_tot, y_tot = init_data(D)
X_tot = np.insert(X_tot, 0, 1, axis=1)

#Generate labels matrix
labels = D[:, -1]
y = np.zeros([len(X_tot), 2])

In [13]:
for i in range(len(labels)):
    if labels[i] == 1:
        y[i,1] = 1.0
    elif labels[i] == 0:
        y[i,0] = 1.0

hidden_neurons = 400
output_neurons = 2

In [14]:
#K fold cross validation
#Gaussian activation function
print("Gaussian accuracies: ")
acc = 0
for k in range(5):

    X_train = X_tot[0 : 1718]
    y_train = y[0 : 1718]
    X_val = X_tot[1718 :]
    y_val = y[1718 :]
    
    a = np.random.rand(X_train.shape[1], hidden_neurons) 
    b = np.random.rand(hidden_neurons)
    
    # Training 
    H = gaussian(X_train, a, b)
    H_inv = np.linalg.pinv(H)
    W2 = np.matmul(H_inv, y_train)
    
    # Testing
    H_T = gaussian(X_val, a, b)
    y_pred = np.matmul(H_T, W2)
    
    print(f'Fold {k+1}:\n')
    a = [np.argmax(y_pred[i]) for i in range(len(y_pred))]
    b= [np.argmax(y_val[i]) for i in range(len(y_val))]
    confmat = cm(b,a)
    print("Confusion Matrix:\n")
    print(confmat)
    Accuracy = (confmat[0][0]+confmat[1][1])/len(y_val)
    acc += Accuracy
    Sensitivity = (confmat[1][1])/(confmat[1][0] + confmat[1][1])
    Specificity = (confmat[0][0])/(confmat[0][0] + confmat[0][1])
    print(f"Accuracy: {Accuracy}\nSensitivity: {Sensitivity}\nSpecificity: {Specificity}")
    print("=============================================")

    X_tot[0 : 430] = X_val
    X_tot[430 : ] = X_train
    y[0 : 430] = y_val
    y[430 : ] = y_train

print(f"Overall Accuracy: {acc*100/5}%")

Gaussian accuracies: 
Fold 1:

Confusion Matrix:

[[187  21]
 [ 14 208]]
Accuracy: 0.9186046511627907
Sensitivity: 0.9369369369369369
Specificity: 0.8990384615384616
Fold 2:

Confusion Matrix:

[[182  38]
 [ 16 194]]
Accuracy: 0.8744186046511628
Sensitivity: 0.9238095238095239
Specificity: 0.8272727272727273
Fold 3:

Confusion Matrix:

[[205  24]
 [ 20 181]]
Accuracy: 0.8976744186046511
Sensitivity: 0.900497512437811
Specificity: 0.8951965065502183
Fold 4:

Confusion Matrix:

[[190  25]
 [ 21 194]]
Accuracy: 0.8930232558139535
Sensitivity: 0.9023255813953488
Specificity: 0.8837209302325582
Fold 5:

Confusion Matrix:

[[181  27]
 [ 20 202]]
Accuracy: 0.8906976744186047
Sensitivity: 0.9099099099099099
Specificity: 0.8701923076923077
Overall Accuracy: 89.48837209302326%


In [15]:
#Tanh activation function
y_pred_full = []
print("Tanh accuracies:\n")
acc = 0
for k in range(5):
    
    X_train = X_tot[0 : 1718]
    y_train = y[0 : 1718]
    X_val = X_tot[1718 :]
    y_val = y[1718 :]
    
    a = np.random.rand(X_train.shape[1],hidden_neurons) 
    b = np.random.rand(hidden_neurons)
    
    # Training 
    H = tanh(X_train)
    H_inv = np.linalg.pinv(H)
    W2 = np.matmul(H_inv, y_train)
    
    # Testing
    H_T = tanh(X_val)
    y_pred = np.matmul(H_T, W2)
    

    # for p in range(len(y_pred)):
    #     if np.argmax(y_pred[p]) == np.argmax(y_val[p]):
    #         accuracy += 1
    #     y_pred_full.append(np.argmax(y_pred[p]))
    # accuracy = accuracy / len(y_pred)

    print(f'Fold {k+1}:\n')
    a = [np.argmax(y_pred[i]) for i in range(len(y_pred))]
    b= [np.argmax(y_val[i]) for i in range(len(y_val))]
    confmat = cm(b,a)
    print("Confusion Matrix:\n")
    print(confmat)
    Accuracy = (confmat[0][0]+confmat[1][1])/len(y_val)
    acc += Accuracy
    Sensitivity = (confmat[1][1])/(confmat[1][0] + confmat[1][1])
    Specificity = (confmat[0][0])/(confmat[0][0] + confmat[0][1])
    print(f"Accuracy: {Accuracy}\nSensitivity: {Sensitivity}\nSpecificity: {Specificity}")
    print("=============================================")
    

    X_tot[0 : 430] = X_val
    X_tot[430 : ] = X_train
    y[0 : 430] = y_val
    y[430 : ] = y_train
print(f"Overall Accuracy: {acc*100/5}%")

Tanh accuracies:

Fold 1:

Confusion Matrix:

[[185  36]
 [ 24 185]]
Accuracy: 0.8604651162790697
Sensitivity: 0.8851674641148325
Specificity: 0.8371040723981901
Fold 2:

Confusion Matrix:

[[184  43]
 [ 34 169]]
Accuracy: 0.8209302325581396
Sensitivity: 0.8325123152709359
Specificity: 0.8105726872246696
Fold 3:

Confusion Matrix:

[[185  31]
 [ 29 185]]
Accuracy: 0.8604651162790697
Sensitivity: 0.8644859813084113
Specificity: 0.8564814814814815
Fold 4:

Confusion Matrix:

[[171  36]
 [ 41 182]]
Accuracy: 0.8209302325581396
Sensitivity: 0.8161434977578476
Specificity: 0.8260869565217391
Fold 5:

Confusion Matrix:

[[186  36]
 [ 24 184]]
Accuracy: 0.8604651162790697
Sensitivity: 0.8846153846153846
Specificity: 0.8378378378378378
Overall Accuracy: 84.46511627906978%
