<a href="https://colab.research.google.com/github/SanePai/Neural_Networks-Assignment-2/blob/main/Question_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%cd "/content/drive/MyDrive/NNFL/Assignment 2"
!ls

/content/drive/.shortcut-targets-by-id/104/Assignment 2
assignment2.pdf  data55.xlsx  input_a2.mat  label.mat
class_label.mat  data5.mat    input.mat


In [ ]:
import numpy as np 
from scipy.io import loadmat
from sklearn.preprocessing import normalize
import random
from sklearn.metrics import confusion_matrix as cm

In [ ]:
#Gaussian activation function
def gaussian(X, a, b):   
    K = np.zeros((X.shape[0], hidden_neurons))
    for i in range(K.shape[0]):
        for j in range(K.shape[1]):
            K[i,j] = np.exp(-b[j] * np.linalg.norm(a[:,j] - X[i,:]))  
    return K

#Tanh activation function
def tanh(X):
    return np.tanh(X)

#Load data, shuffle and normalize
def init_data(data):
    X = np.array(data[ : , :-1], dtype = float)
    y = np.array(data[ : , -1], dtype = int)
    X = normalize(X, axis = 0)
    return X, y

In [ ]:
f = loadmat('data5.mat')
D = f['x']
np.random.shuffle(D)

X_tot, y_tot = init_data(D)
X_tot = np.insert(X_tot, 0, 1, axis=1)

#Generate labels matrix
labels = D[:, -1]
y = np.zeros([len(X_tot), 2])

In [ ]:
for i in range(len(labels)):
    if labels[i] == 1:
        y[i,1] = 1.0
    elif labels[i] == 0:
        y[i,0] = 1.0

hidden_neurons = 100
output_neurons = 2

In [ ]:
#K fold cross validation
#Gaussian activation function
print("Gaussian accuracies: ")
for k in range(6):

    X_train = X_tot[0 : 1790]
    y_train = y[0 : 1790]
    X_val = X_tot[1790 :]
    y_val = y[1790 :]
    
    a = np.random.rand(X_train.shape[1], hidden_neurons) 
    b = np.random.rand(hidden_neurons)
    
    # Training 
    H = gaussian(X_train, a, b)
    H_inv = np.linalg.pinv(H)
    W2 = np.matmul(H_inv, y_train)
    
    # Testing
    H_T = gaussian(X_val, a, b)
    y_pred = np.matmul(H_T, W2)
    
    print(f'Fold {k+1}:\n')
    a = [np.argmax(y_pred[i]) for i in range(len(y_pred))]
    b= [np.argmax(y_val[i]) for i in range(len(y_val))]
    confmat = cm(b,a)
    print("Confusion Matrix:\n")
    print(confmat)
    Accuracy = (confmat[0][0]+confmat[1][1])/len(y_val)
    Sensitivity = (confmat[1][1])/(confmat[1][0] + confmat[1][1])
    Specificity = (confmat[0][0])/(confmat[0][0] + confmat[0][1])
    print(f"Accuracy: {Accuracy}\nSensitivity: {Sensitivity}\nSpecificity: {Specificity}")
    print("=============================================")

    X_tot[0 : 358] = X_val
    X_tot[358 : ] = X_train
    y[0 : 358] = y_val
    y[358 : ] = y_train



Gaussian accuracies: 
Fold 1:

Confusion Matrix:

[[158  28]
 [ 26 146]]
Accuracy: 0.8491620111731844
Sensitivity: 0.8488372093023255
Specificity: 0.8494623655913979
Fold 2:

Confusion Matrix:

[[148  24]
 [ 18 168]]
Accuracy: 0.88268156424581
Sensitivity: 0.9032258064516129
Specificity: 0.8604651162790697
Fold 3:

Confusion Matrix:

[[153  31]
 [ 23 151]]
Accuracy: 0.8491620111731844
Sensitivity: 0.867816091954023
Specificity: 0.8315217391304348
Fold 4:

Confusion Matrix:

[[154  25]
 [ 21 158]]
Accuracy: 0.8715083798882681
Sensitivity: 0.88268156424581
Specificity: 0.8603351955307262
Fold 5:

Confusion Matrix:

[[153  20]
 [ 21 164]]
Accuracy: 0.8854748603351955
Sensitivity: 0.8864864864864865
Specificity: 0.884393063583815
Fold 6:

Confusion Matrix:

[[159  27]
 [ 26 146]]
Accuracy: 0.8519553072625698
Sensitivity: 0.8488372093023255
Specificity: 0.8548387096774194


In [ ]:
#Tanh activation function
y_pred_full = []
print("Tanh accuracies:\n")
for k in range(6):
    
    X_train = X_tot[0 : 1790]
    y_train = y[0 : 1790]
    X_val = X_tot[1790 :]
    y_val = y[1790 :]
    
    a = np.random.rand(X_train.shape[1],hidden_neurons) 
    b = np.random.rand(hidden_neurons)
    
    # Training 
    H = tanh(X_train)
    H_inv = np.linalg.pinv(H)
    W2 = np.matmul(H_inv, y_train)
    
    # Testing
    H_T = tanh(X_val)
    y_pred = np.matmul(H_T, W2)
    

    # for p in range(len(y_pred)):
    #     if np.argmax(y_pred[p]) == np.argmax(y_val[p]):
    #         accuracy += 1
    #     y_pred_full.append(np.argmax(y_pred[p]))
    # accuracy = accuracy / len(y_pred)

    print(f'Fold {k+1}:\n')
    a = [np.argmax(y_pred[i]) for i in range(len(y_pred))]
    b= [np.argmax(y_val[i]) for i in range(len(y_val))]
    confmat = cm(b,a)
    print("Confusion Matrix:\n")
    print(confmat)
    Accuracy = (confmat[0][0]+confmat[1][1])/len(y_val)
    Sensitivity = (confmat[1][1])/(confmat[1][0] + confmat[1][1])
    Specificity = (confmat[0][0])/(confmat[0][0] + confmat[0][1])
    print(f"Accuracy: {Accuracy}\nSensitivity: {Sensitivity}\nSpecificity: {Specificity}")
    print("=============================================")
    

    X_tot[0 : 358] = X_val
    X_tot[358 : ] = X_train
    y[0 : 358] = y_val
    y[358 : ] = y_train


Tanh accuracies:

Fold 1:

Confusion Matrix:

[[137  35]
 [ 28 158]]
Accuracy: 0.8240223463687151
Sensitivity: 0.8494623655913979
Specificity: 0.7965116279069767
Fold 2:

Confusion Matrix:

[[149  35]
 [ 28 146]]
Accuracy: 0.8240223463687151
Sensitivity: 0.8390804597701149
Specificity: 0.8097826086956522
Fold 3:

Confusion Matrix:

[[147  32]
 [ 17 162]]
Accuracy: 0.8631284916201117
Sensitivity: 0.9050279329608939
Specificity: 0.8212290502793296
Fold 4:

Confusion Matrix:

[[147  26]
 [ 28 157]]
Accuracy: 0.8491620111731844
Sensitivity: 0.8486486486486486
Specificity: 0.8497109826589595
Fold 5:

Confusion Matrix:

[[155  31]
 [ 33 139]]
Accuracy: 0.8212290502793296
Sensitivity: 0.8081395348837209
Specificity: 0.8333333333333334
Fold 6:

Confusion Matrix:

[[137  35]
 [ 28 158]]
Accuracy: 0.8240223463687151
Sensitivity: 0.8494623655913979
Specificity: 0.7965116279069767
